name: AzusaHideSystemUI
version: 1.0.2
api: [5.0.0]
main: KumaDev\HideSystem\Main
author: KumaDeveloper
description: Plugin that removes nametags of other players or skins of other players
commands:
  hidesystem:
    description: Open AzusaHideSystemUI
    aliases: [hsystem, hs]
    permission: azusahidesystemui.command
permissions:
  azusahidesystemui.command:
    description: Allows players to use the AzusaHideSystemUI
    default: true
dependencies:
- FormAPI
